app = "mixtures"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = "./bin/release.sh"

[env]
  DJANGO_LOG_LEVEL = "WARN"
  DJANGO_SETTINGS_MODULE = "mixtures.settings_deploy"

[processes]
  web = "./bin/launch.sh"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
