# Generated by Django 4.1.9 on 2023-07-10 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_alter_article_author'), ('blog', '0003_alter_article_created_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modification')),
                ('slug', models.SlugField(unique=True, verbose_name='identifier')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('title_fr', models.CharField(max_length=128, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='title')),
                ('content', models.TextField(help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='content')),
                ('content_fr', models.TextField(help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='content')),
                ('content_en', models.TextField(help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='content')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation')),
                ('last_modified', models.DateTimeField(blank=True, editable=False, verbose_name='last modification')),
                ('slug', models.SlugField(verbose_name='identifier')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('title_fr', models.CharField(max_length=128, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='title')),
                ('content', models.TextField(help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='content')),
                ('content_fr', models.TextField(help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='content')),
                ('content_en', models.TextField(help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='content')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical article',
                'verbose_name_plural': 'historical articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
