# Generated by Django 3.0.6 on 2020-08-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugcombinator', '0030_historicaldrug_historicalinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nom')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal', to='drugcombinator.Drug', verbose_name='substance')),
            ],
            options={
                'verbose_name': 'portail',
            },
        ),
    ]
