# Generated by Django 3.1.6 on 2021-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugportals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='portal',
            name='name_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='nom'),
        ),
    ]
