# Generated by Django 3.1.6 on 2021-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugportals', '0002_auto_20210326_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portal',
            options={'verbose_name': 'portal'},
        ),
        migrations.AlterField(
            model_name='portal',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='name_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
    ]
