# Generated by Django 2.2.10 on 2020-03-25 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'verbose_name': 'interaction'},
        ),
        migrations.AlterField(
            model_name='drug',
            name='interactants',
            field=models.ManyToManyField(through='drugcombinator.Interaction', to='drugcombinator.Drug', verbose_name='interactants'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='effect_description',
            field=models.TextField(blank=True, default='', verbose_name='description des effets'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='from_substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_interaction+', to='drugcombinator.Drug', verbose_name='première substance'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='pharmaco',
            field=models.IntegerField(choices=[(0, 'Inconnue'), (1, 'Neutre'), (2, 'Atténuation'), (3, 'Potentialisation'), (4, 'Mixte')], default=0, verbose_name='pharmacologie'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='risk_description',
            field=models.TextField(blank=True, default='', verbose_name='description des risques'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='to_substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_interaction+', to='drugcombinator.Drug', verbose_name='seconde substance'),
        ),
    ]
