# Generated by Django 2.2.10 on 2020-03-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0002_auto_20200325_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='sym_id',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
