# Generated by Django 2.2.10 on 2020-03-26 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0003_auto_20200326_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='ajouté')),
                ('name', models.CharField(max_length=128, verbose_name='nom')),
                ('slug', models.SlugField(unique=True, verbose_name='identifiant')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'catégorie',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substances', to='drugcombinator.Category', verbose_name='catégorie'),
        ),
    ]
