# Generated by Django 2.2.10 on 2020-03-27 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0004_auto_20200326_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substances', to='drugcombinator.Category', verbose_name='catégorie'),
        ),
    ]
