# Generated by Django 2.2.10 on 2020-03-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0006_auto_20200330_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ('name',), 'verbose_name': 'substance'},
        ),
        migrations.AddField(
            model_name='drug',
            name='common',
            field=models.BooleanField(default=True, help_text="Les substances communes sont affichées sous forme de boutons dans l'app.", verbose_name='Commune'),
        ),
    ]
