# Generated by Django 2.2.10 on 2020-04-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0007_auto_20200331_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True, default='', help_text="Ce champ n'est visible que sur ce site d'administration et est partagé entre tous les utilisateurs.", verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='common',
            field=models.BooleanField(default=True, help_text="Les substances communes sont affichées sous forme de boutons dans l'app.", verbose_name='commune'),
        ),
    ]
