# Generated by Django 2.2.10 on 2020-04-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0008_auto_20200406_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, default='', help_text='La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='effect_description',
            field=models.TextField(blank=True, default='', help_text='La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', verbose_name='description des effets'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='risk_description',
            field=models.TextField(blank=True, default='', help_text='La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', verbose_name='description des risques'),
        ),
    ]
