# Generated by Django 2.2.10 on 2020-04-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0009_auto_20200410_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='pharmaco',
            new_name='synergy',
        ),
    ]
