# Generated by Django 2.2.10 on 2020-04-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0011_auto_20200424_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='synergy',
            field=models.IntegerField(choices=[(0, 'Inconnue'), (1, 'Neutre'), (5, 'Addition'), (2, 'Atténuation'), (3, 'Potentialisation'), (4, 'Mixte')], default=0, verbose_name='synergie'),
        ),
    ]
