# Generated by Django 2.2.10 on 2020-04-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0014_interaction_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='En cas de travail en cours, de données incertaines ou incomplètes.', verbose_name='brouillon'),
        ),
    ]
