# Generated by Django 2.2.10 on 2020-04-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0015_auto_20200425_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='ajouté')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modifié')),
                ('title', models.CharField(default='Note sans titre', max_length=128, verbose_name='titre')),
                ('content', models.TextField(blank=True, default='', help_text="Les notes ne sont visibles que sur ce site d'administration et sont partagées entre tous les utilisateurs.", verbose_name='contenu')),
                ('related_drugs', models.ManyToManyField(help_text='Si cette note concerne des substances particulières, vous pouvez optionellement les spécifier ici.', related_name='notes', to='drugcombinator.Drug', verbose_name='substances concernées')),
            ],
            options={
                'verbose_name': 'note',
            },
        ),
    ]
