# Generated by Django 2.2.10 on 2020-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0016_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='related_drugs',
            field=models.ManyToManyField(blank=True, help_text='Si cette note concerne des substances particulières, vous pouvez optionellement les spécifier ici.', related_name='notes', to='drugcombinator.Drug', verbose_name='substances concernées'),
        ),
    ]
