# Generated by Django 2.2.10 on 2020-05-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0017_auto_20200426_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='risks',
            field=models.TextField(blank=True, default='', help_text='Risques ou précautions spécifiques à cette substance qui ne dépendent pas d\'une interaction particulière.\nLa syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', verbose_name='risques généraux'),
        ),
    ]
