# Generated by Django 2.2.10 on 2020-05-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0019_auto_20200501_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='effects',
            field=models.TextField(blank=True, default='', help_text='Effets spécifiques à la combinaison de cette substance qui ne dépendent pas d\'une interaction particulière.<br/>La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', verbose_name='effets généraux'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='risks',
            field=models.TextField(blank=True, default='', help_text='Risques spécifiques à la combinaison de cette substance qui ne dépendent pas d\'une interaction particulière.<br/>La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', verbose_name='risques généraux'),
        ),
    ]
