# Generated by Django 3.0.6 on 2020-05-04 15:00

from django.db import migrations


def delete_duplicate_interactions(apps, schema_editor):

    Interaction = apps.get_model('drugcombinator', 'Interaction')
    sym_ids = []
    for inter in Interaction.objects.all():
        if inter.sym_id in sym_ids:
            inter.delete()
        else:
            sym_ids.append(inter.sym_id)

        
class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0020_auto_20200502_0112'),
    ]

    migrations.RunPython(delete_duplicate_interactions),

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='sym_id',
        ),
    ]
