# Generated by Django 3.0.6 on 2020-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0021_remove_interaction_sym_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='interactants',
            field=models.ManyToManyField(related_name='_drug_interactants_+', through='drugcombinator.Interaction', to='drugcombinator.Drug', verbose_name='interactants'),
        ),
    ]
