# Generated by Django 3.0.6 on 2020-05-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0022_auto_20200504_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='from_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_from', to='drugcombinator.Drug', verbose_name='première substance'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='to_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_to', to='drugcombinator.Drug', verbose_name='seconde substance'),
        ),
    ]
