# Generated by Django 3.0.6 on 2020-05-06 11:18

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0023_auto_20200504_1835'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, from_drug=django.db.models.expressions.F('to_drug')), name='interactants_inequals'),
        ),
    ]
