# Generated by Django 3.0.6 on 2020-05-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0025_auto_20200506_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='effects_reliability',
            field=models.IntegerField(choices=[(0, 'Non évalué'), (1, 'Théorique'), (2, 'Supposé'), (3, 'Avéré')], default=0, verbose_name='fiabilité de la synergie et des effets'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='risk_reliability',
            field=models.IntegerField(choices=[(0, 'Non évalué'), (1, 'Théorique'), (2, 'Supposé'), (3, 'Avéré')], default=0, verbose_name='fiabilité des risques'),
        ),
    ]
