# Generated by Django 3.0.6 on 2020-05-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0026_auto_20200509_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='effects_reliability',
            field=models.IntegerField(choices=[(0, 'Non évaluée'), (1, 'Théorique'), (2, 'Supposée'), (3, 'Avérée')], default=0, verbose_name='fiabilité de la synergie et des effets'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='risk_reliability',
            field=models.IntegerField(choices=[(0, 'Non évaluée'), (1, 'Théorique'), (2, 'Supposée'), (3, 'Avérée')], default=0, verbose_name='fiabilité des risques'),
        ),
    ]
