# Generated by Django 3.0.6 on 2020-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0027_auto_20200509_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='added',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='added',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='added',
        ),
        migrations.RemoveField(
            model_name='note',
            name='added',
        ),
        migrations.RemoveField(
            model_name='note',
            name='modified',
        ),
        migrations.AddField(
            model_name='category',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ajouté'),
        ),
        migrations.AddField(
            model_name='drug',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ajouté'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ajouté'),
        ),
        migrations.AddField(
            model_name='note',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ajouté'),
        ),
    ]
