# Generated by Django 3.1.6 on 2021-03-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0031_auto_20210325_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldrug',
            name='_aliases_en',
            field=models.TextField(blank=True, default='', help_text='Un alias par ligne. Insensible à la casse.', null=True, verbose_name='dénominations'),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='_aliases_fr',
            field=models.TextField(blank=True, default='', help_text='Un alias par ligne. Insensible à la casse.', null=True, verbose_name='dénominations'),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='description_fr',
            field=models.TextField(blank=True, default='', help_text='La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='effects_en',
            field=models.TextField(blank=True, default='', help_text='Effets spécifiques à la combinaison de cette substance qui ne dépendent pas d\'une interaction particulière.<br/>La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='effets généraux'),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='effects_fr',
            field=models.TextField(blank=True, default='', help_text='Effets spécifiques à la combinaison de cette substance qui ne dépendent pas d\'une interaction particulière.<br/>La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='effets généraux'),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='name_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='risks_en',
            field=models.TextField(blank=True, default='', help_text='Risques spécifiques à la combinaison de cette substance qui ne dépendent pas d\'une interaction particulière.<br/>La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='risques généraux'),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='risks_fr',
            field=models.TextField(blank=True, default='', help_text='Risques spécifiques à la combinaison de cette substance qui ne dépendent pas d\'une interaction particulière.<br/>La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='risques généraux'),
        ),
        migrations.AddField(
            model_name='historicalinteraction',
            name='effect_description_en',
            field=models.TextField(blank=True, default='', help_text='La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='description des effets'),
        ),
        migrations.AddField(
            model_name='historicalinteraction',
            name='effect_description_fr',
            field=models.TextField(blank=True, default='', help_text='La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='description des effets'),
        ),
        migrations.AddField(
            model_name='historicalinteraction',
            name='risk_description_en',
            field=models.TextField(blank=True, default='', help_text='La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='description des risques'),
        ),
        migrations.AddField(
            model_name='historicalinteraction',
            name='risk_description_fr',
            field=models.TextField(blank=True, default='', help_text='La syntaxe <a href="https://commonmark.org/help/">markdown</a> est autorisée. Les paragraphes sont séparés par deux retours à la ligne.', null=True, verbose_name='description des risques'),
        ),
    ]
