# Generated by Django 3.1.6 on 2021-04-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0032_auto_20210326_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ('slug',), 'verbose_name': 'substance'},
        ),
        migrations.AlterField(
            model_name='category',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='_aliases',
            field=models.TextField(blank=True, default='', help_text='One alias per line. No need to duplicate case.', verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='_aliases_en',
            field=models.TextField(blank=True, default='', help_text='One alias per line. No need to duplicate case.', null=True, verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='_aliases_fr',
            field=models.TextField(blank=True, default='', help_text='One alias per line. No need to duplicate case.', null=True, verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='drugcombinator.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='common',
            field=models.BooleanField(default=True, help_text='Common substances are displayed as buttons in the app.', verbose_name='common'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='description_fr',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='effects',
            field=models.TextField(blank=True, default='', help_text='Effects specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='general effects'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='effects_en',
            field=models.TextField(blank=True, default='', help_text='Effects specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='general effects'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='effects_fr',
            field=models.TextField(blank=True, default='', help_text='Effects specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='general effects'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='risks',
            field=models.TextField(blank=True, default='', help_text='Risks specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='general risks'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='risks_en',
            field=models.TextField(blank=True, default='', help_text='Risks specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='general risks'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='risks_fr',
            field=models.TextField(blank=True, default='', help_text='Risks specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='general risks'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='_aliases',
            field=models.TextField(blank=True, default='', help_text='One alias per line. No need to duplicate case.', verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='_aliases_en',
            field=models.TextField(blank=True, default='', help_text='One alias per line. No need to duplicate case.', null=True, verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='_aliases_fr',
            field=models.TextField(blank=True, default='', help_text='One alias per line. No need to duplicate case.', null=True, verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='drugcombinator.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='common',
            field=models.BooleanField(default=True, help_text='Common substances are displayed as buttons in the app.', verbose_name='common'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='description_fr',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='effects',
            field=models.TextField(blank=True, default='', help_text='Effects specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='general effects'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='effects_en',
            field=models.TextField(blank=True, default='', help_text='Effects specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='general effects'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='effects_fr',
            field=models.TextField(blank=True, default='', help_text='Effects specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='general effects'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last modification'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='name_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='risks',
            field=models.TextField(blank=True, default='', help_text='Risks specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='general risks'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='risks_en',
            field=models.TextField(blank=True, default='', help_text='Risks specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='general risks'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='risks_fr',
            field=models.TextField(blank=True, default='', help_text='Risks specific to combinations involving this substance that do not depend on a specific interaction.<br/>The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='general risks'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='slug',
            field=models.SlugField(verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='effect_description',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='effects description'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='effect_description_en',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='effects description'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='effect_description_fr',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='effects description'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='effects_reliability',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Hypothetical'), (2, 'Inferred'), (3, 'Proven')], default=0, verbose_name='synergy and effects reliability'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='from_drug',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='drugcombinator.drug', verbose_name='first interactant'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='In case of work-in-progress, uncertain or incomplete data.', verbose_name='draft'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last modification'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='This field is only displayed on this admin site and is shared between all users and languages.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='risk',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Neutral'), (2, 'Caution'), (3, 'Unsafe'), (4, 'Dangerous')], default=0, verbose_name='risks'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='risk_description',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='risks description'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='risk_description_en',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='risks description'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='risk_description_fr',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='risks description'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='risk_reliability',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Hypothetical'), (2, 'Inferred'), (3, 'Proven')], default=0, verbose_name='risks reliability'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='synergy',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Neutral'), (5, 'Additive'), (2, 'Decrease'), (3, 'Increase'), (4, 'Mixed')], default=0, verbose_name='synergy'),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='to_drug',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='drugcombinator.drug', verbose_name='second interactant'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='effect_description',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='effects description'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='effect_description_en',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='effects description'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='effect_description_fr',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='effects description'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='effects_reliability',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Hypothetical'), (2, 'Inferred'), (3, 'Proven')], default=0, verbose_name='synergy and effects reliability'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='from_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_from', to='drugcombinator.drug', verbose_name='first interactant'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='In case of work-in-progress, uncertain or incomplete data.', verbose_name='draft'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='This field is only displayed on this admin site and is shared between all users and languages.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='risk',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Neutral'), (2, 'Caution'), (3, 'Unsafe'), (4, 'Dangerous')], default=0, verbose_name='risks'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='risk_description',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', verbose_name='risks description'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='risk_description_en',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='risks description'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='risk_description_fr',
            field=models.TextField(blank=True, default='', help_text='The <a href="https://commonmark.org/help/">markdown</a> syntax is allowed. Paragraphs are separated by two carriage returns.', null=True, verbose_name='risks description'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='risk_reliability',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Hypothetical'), (2, 'Inferred'), (3, 'Proven')], default=0, verbose_name='risks reliability'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='synergy',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Neutral'), (5, 'Additive'), (2, 'Decrease'), (3, 'Increase'), (4, 'Mixed')], default=0, verbose_name='synergy'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='to_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_to', to='drugcombinator.drug', verbose_name='second interactant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Notes are only displayed on this admin site and are shared between all users and languages.', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification'),
        ),
        migrations.AlterField(
            model_name='note',
            name='related_drugs',
            field=models.ManyToManyField(blank=True, help_text='If this note involves specific substances, you can optionally set them here.', related_name='notes', to='drugcombinator.Drug', verbose_name='involved substances'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Untitled note', max_length=128, verbose_name='title'),
        ),
    ]
