# Generated by Django 3.1.8 on 2021-07-16 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugcombinator', '0033_auto_20210403_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.URLField(blank=True, default='', max_length=128, verbose_name='personal page')),
                ('display', models.BooleanField(default=False, verbose_name='show in about page')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'contributor profile',
                'verbose_name_plural': 'contributor profiles',
            },
        ),
    ]
