# Generated by Django 3.1.8 on 2021-07-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0034_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='page',
            field=models.URLField(blank=True, default='', help_text='This link may be used in public contributors lists.', max_length=128, verbose_name='personal page'),
        ),
    ]
