# Generated by Django 3.1.8 on 2021-07-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0035_auto_20210717_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='display',
            field=models.BooleanField(default=False, help_text='Show this profile in public contributors lists.', verbose_name='show publicly'),
        ),
    ]
