# Generated by Django 3.1.8 on 2022-08-13 15:08

from django.db import migrations
import drugcombinator.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0036_auto_20210717_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinteraction',
            name='names',
            field=drugcombinator.modelfields.ListField(help_text='One name per line. The first one can be emphasized in the app.', verbose_name='slang names'),
        ),
        migrations.AddField(
            model_name='historicalinteraction',
            name='names_en',
            field=drugcombinator.modelfields.ListField(help_text='One name per line. The first one can be emphasized in the app.', null=True, verbose_name='slang names'),
        ),
        migrations.AddField(
            model_name='historicalinteraction',
            name='names_fr',
            field=drugcombinator.modelfields.ListField(help_text='One name per line. The first one can be emphasized in the app.', null=True, verbose_name='slang names'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='names',
            field=drugcombinator.modelfields.ListField(help_text='One name per line. The first one can be emphasized in the app.', verbose_name='slang names'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='names_en',
            field=drugcombinator.modelfields.ListField(help_text='One name per line. The first one can be emphasized in the app.', null=True, verbose_name='slang names'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='names_fr',
            field=drugcombinator.modelfields.ListField(help_text='One name per line. The first one can be emphasized in the app.', null=True, verbose_name='slang names'),
        ),
    ]
