# Generated by Django 4.1 on 2022-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0037_auto_20220813_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldrug',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical substance', 'verbose_name_plural': 'historical substances'},
        ),
        migrations.AlterModelOptions(
            name='historicalinteraction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical interaction', 'verbose_name_plural': 'historical interactions'},
        ),
        migrations.AlterField(
            model_name='drug',
            name='interactants',
            field=models.ManyToManyField(through='drugcombinator.Interaction', to='drugcombinator.drug', verbose_name='interactants'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinteraction',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
