# Generated by Django 4.1 on 2022-08-17 19:57

from django.db import migrations
import drugcombinator.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0039_rename__aliases_drug_aliases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='aliases',
            field=drugcombinator.modelfields.ListField(default=[], help_text='One alias per line. No need to duplicate case.', verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='aliases_en',
            field=drugcombinator.modelfields.ListField(default=[], help_text='One alias per line. No need to duplicate case.', null=True, verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='aliases_fr',
            field=drugcombinator.modelfields.ListField(default=[], help_text='One alias per line. No need to duplicate case.', null=True, verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='aliases',
            field=drugcombinator.modelfields.ListField(default=[], help_text='One alias per line. No need to duplicate case.', verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='aliases_en',
            field=drugcombinator.modelfields.ListField(default=[], help_text='One alias per line. No need to duplicate case.', null=True, verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='aliases_fr',
            field=drugcombinator.modelfields.ListField(default=[], help_text='One alias per line. No need to duplicate case.', null=True, verbose_name='aliases'),
        ),
    ]
