# Generated by Django 4.1 on 2022-08-17 20:36

from django.db import migrations


def trim_aliases(apps, schema_editor):
    Drug = apps.get_model('drugcombinator', 'Drug')
    fields = ('aliases', 'aliases_en', 'aliases_fr')
    
    for drug in Drug.objects.all():
        for field in fields:
            aliases = getattr(drug, field)
            setattr(drug, field, [a.strip() for a in aliases])
            drug.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0040_alter_drug_aliases_alter_drug_aliases_en_and_more'),
    ]

    operations = [
        migrations.RunPython(trim_aliases),
    ]
