# Generated by Django 4.1.7 on 2023-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0041_trim_drug_aliases_20220817_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinteraction',
            name='uris',
            field=models.JSONField(default=dict, editable=False, help_text='URIs extracted from these interaction data texts, mapped to their last Wayback Machine snapshot date.', verbose_name='URIs'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='uris',
            field=models.JSONField(default=dict, editable=False, help_text='URIs extracted from these interaction data texts, mapped to their last Wayback Machine snapshot date.', verbose_name='URIs'),
        ),
    ]
