# Generated by Django 4.1.7 on 2023-03-19 10:02

from django.db import migrations

from drugcombinator.business.wayback import to_datetime


def update_ts(apps, schema_editor):
    Interaction = apps.get_model('drugcombinator', 'Interaction')
    
    for inter in Interaction.objects.all():
        for uri, meta in inter.uris.items():
            if meta is None:
                continue
            
            date = meta.get('date', None)

            if isinstance(date, str):
                inter.uris[uri]['date'] = to_datetime(date).timestamp()

        inter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drugcombinator', '0042_historicalinteraction_uris_interaction_uris'),
    ]

    operations = [
        migrations.RunPython(update_ts),
    ]
