# Build and deploy Django app on fly.io
name: Build Django app

on:
  push:
    branches: ["master"]

concurrency:
  group: "flyio"
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.6
      - name: Set up gettext
        run: sudo apt install gettext
      - name: Install dev dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Compile messages
        run: python ./manage.py compilemessages --noinput

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
