# Build and deploy Django app on fly.io
name: Build Django app

on:
  push:
    branches: ["master"]

concurrency:
  group: "flyio"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up gettext
        run: sudo apt install gettext
      - name: Install dev dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Compile messages
        run: pipenv run python ./manage.py compilemessages
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: '.'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: package
      - name: Set up fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
