# Build and deploy Django app on fly.io
name: App deploy

on:
  push:
    branches: ["master"]

concurrency:
  group: "flyio"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Set up fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
